name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: sudo docker pull strato2024/flask-demo:latest
      
      - name: Delete Old Docker Container
        run: sudo docker rm -f cicd-pipeline-cont || true

      - name: Pull Docker Image
        run: sudo docker run -d -p 8080:5000 --name cicd-pipeline-cont strato2024/flask-demo